# User.create(name: 'administrator', email: 'admin@admin.com', password: 'password',
#             password_confirmation: 'password')
# Admin.create(user_id: 1)


names = [
  'Agatha Follansbee',
  'Salena Bakewell',
  'Hank Rustad',
  'Malissa Acquaviva',
  'Kris Stall',
  'Asley Tobia',
  'Johnathan Vesey',
  'Crissy Ines',
  'Evette Sage',
  'Brenna Wingard',
  'Dorine Vien',
  'Shira Garofalo',
  'Lelah Orozco',
  'Katia Countryman',
  'Rosalee Bellanger',
  'Kristina Nowland',
  'Bess Corchado',
  'Lisandra Bedsole',
  'Kaitlyn Riding',
  'Darcie Paschke',
  'Evonne Laswell',
  'Helene Worthington',
  'Tova Grist',
  'Nada Fenley',
  'Trent Hassell',
  'Dwain Ryles',
  'Rebbeca Bezio',
  'Amado Motes',
  'Tynisha Nees',
  'Yevette Pro',
  'Nu Stokely',
  'Jestine Barringer',
  'Earline Dicicco',
  'Hugh Ristau',
  'Verla Tokarski',
  'Shera Gordillo',
  'Deandre Mcmillan',
  'Mohamed Hollier',
  'Raphael Pichette',
  'Arielle Kilbourne',
  'Pearlie Decamp',
  'Roxanne Stoute',
  'Hung Dollinger',
  'Clarinda Mahnke',
  'Eryn Demaio',
  'Evelyn Debonis',
  'Timika Pharris',
  'Jin Leffler',
  'Viviana Lefever',
  'Kimiko Hofman',
  'Rosalia Mckamie',
  'Jetta Kinnard',
  'Stanford Falcone',
  'Denese Whitlock',
  'Lourdes Fertig',
  'Layne Boothe',
  'Malorie Conlan',
  'Larae Bush',
  'Merrie Sabol',
  'Rosaura Eames',
  'Jan Collison',
  'Felice Linden',
  'Chassidy Souther',
  'Dave Scheuermann',
  'Bee Ruge',
  'Ernesto Waldner',
  'Juliane Bono',
  'Salvatore Soderlund',
  'Hubert Hyder',
  'Delphine Blackshear',
  'Valda Arzate',
  'Denver Weiser',
  'Isaiah Litchford',
  'Crysta Jin',
  'Jinny Pankow',
  'Lakeshia Fahie',
  'Willia Steinhoff',
  'Loriann Vena',
  'Kristeen Katzman',
  'Vannessa Southwi',
  'Gianna Welke',
  'Ileana Musgrave',
  'Rosalee Sides',
  'Tajuana Dammann',
  'Delena Crossett',
  'Pansy Rine',
  'Deb Mcvay',
  'Modesto Newcomb',
  'Carlyn Miller',
  'Tiara Effinger',
  'Mindy Wicklund',
  'Len Birney',
  'Shanell Knotts',
  'Donnetta Thresher',
  'Eugenio Harbor',
  'Marianela Kina',
  'Penney Esquilin',
  'Brian Malbon',
  'Carolina Lykins',
  'Vennie Bonnette',
  'Johnna Hetrick',
  'Benny Gregorio',
  'Wilhelmina Markwell',
  'Ina Frates',
  'Ethelene Shasteen',
  'Jeannetta Cottrill',
  'Kareem Mcnamara',
  'Leslie Wisecarver',
  'Luciano Attaway',
  'Beaulah Gersten',
  'Joel Barnhill',
  'Gillian Thode',
  'Ada Tolman',
  'Hien Pantano',
  'Pa Sugar',
  'Patti Vause',
  'Latrisha Knauss',
  'Arnetta Younts',
  'Alex Geier',
  'Samantha Stlouis',
  'Elisa Bracco',
  'Darnell Rippel',
  'Mollie Muise',
  'Clinton Oden',
  'Sherrie Hodgson',
  'Luella Finkelstein',
  'Sharleen Skiles',
  'Tenesha Shur',
  'Freda Bartling',
  'Jacklyn Dobbins '
]

200.times do
  name = names.sample
  user = User.new(
    name: name, email: "#{name.split(' ')[0]}@site.com",
    password: 'password', password_confirmation: 'password',
    phone: rand(100000000..900000000)
  )
  user.save if user.valid?
end